### ISSUE TITLE
MG+MIS Evaluation For Domain Expert

### ISSUE THREAD

**Issue by morteza-im** [mirzaim/ipcs#15]
The MG+MIS documents are ready for evaluation.

[MG.pdf](https://github.com/mirzaim/ipcs/blob/main/docs/Design/SoftArchitecture/MG.pdf)

[MIS.pdf](https://github.com/mirzaim/ipcs/blob/main/docs/Design/SoftDetailedDes/MIS.pdf)

**Comment by alimousavi1997** [comment]
Hello Morteza,
I didn't provide feedback on your MG because it was simple and well-written, except for your Hierarchy diagram. I didn't understand the rationale behind leaving the Sequence Data Structure Module alone. Adding a note about this in your document would be helpful. However, I did make some points on your MIS.
[MIS_review.pdf](https://github.com/mirzaim/ipcs/files/14812851/MIS_review.pdf)
