### ISSUE TITLE
Problem Statement Review

### ISSUE THREAD

**Issue by morteza-im** [mirzaim/ipcs#2]
Please check out [my problem statement](https://github.com/mirzaim/ipcs/tree/main/docs/ProblemStatementAndGoals).

**Comment by smiths** [comment]
Feedback:

- in the future please provide a link directly to the [problem statement](https://github.com/mirzaim/ipcs/blob/main/docs/ProblemStatementAndGoals/ProblemStatement.pdf)
- I believe your equation is from [Wikipedia](https://en.wikipedia.org/wiki/Inverted_pendulum#:~:text=An%20inverted%20pendulum%20on%20a,resulting%20in%20or%20hindering%20motion.)  You should cite your sources.
- The system of equations is incomplete (you are missing the second equation)
- You haven't defined all symbols, and you have defined some that aren't there (like g)
- A figure showing the inverted pendulum would be useful

I don't normally encourage control algorithms in CAS741, but since the simulation of the physics of the inverted pendulum is part of your problem, your project fits with 741.  We'll have to make sure that you don't get too ambitious with the control algorithm so that your project remains feasible.  

Your project is approved.  :smile:
